### ISSUE TITLE
Multiple Disconnects When Resuming WebApp

### ISSUE THREAD

**Issue by wthomsen** [ConnectSDK/Connect-SDK-Cordova-Plugin#8] opened 2014-12-30 09:14 UTC
I'm trying to implement basic resume functionality with a Chromecast webApp:

```
// First try to join an active web app without launching/relaunching
webAppLauncher.joinWebApp(webAppId).success(function (webAppSession) {
  openCommunicationChannel(webAppSession);
}).error(function () {
  // If joining fails, launch instead
  webAppLauncher.launchWebApp(webAppId).success(function (webAppSession) {
    openCommunicationChannel(webAppSession);
  }).error(function (err) {
    console.log('web app launch error: ' + err.message);
  });
});
```

When following:
1. launch webApp
2. kill sender app
3. re-open sender app and join webApp

The join succeeds, but the receiver logs two separate depart (sender disconnection) events, with a join in-between. I believe it is related to https://github.com/ConnectSDK/Connect-SDK-Android-Google-Cast/commit/97fabe8f47a3908d51d70a4060933e48ca97238e, in particular, the addition of `Cast.CastApi.leaveApplication(service.getApiClient());`. When commenting out that line everything works as expected.

What am I missing? Should I somehow be resetting the castServiceChannel before the join, or do I need a new approach entirely?

**Comment by khk624** [comment] 2015-01-16 07:03
Latest c-sdk, we've changed the scenario little bit. 
In the client application side, after you join the web app, you need to setWebAppSessionListener by yourself. 

This issue has been resolved in 
https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin/commit/2bb4ac327a68453378b4874649918fed24d7a52f

and Sampler also has modified in
https://github.com/ConnectSDK/Web-App-Sampler-Cordova/commit/08711122518128337a71b6652f7459ffce47e008

**Comment by khk624** [comment] 2015-01-20 02:20
I'm going to close this, if you have any issue, please re-open this ticket or let us know.

**Closed by khk624** 2015-01-20 02:20 UTC

**Comment by LukePulverenti** [comment] 2015-05-25 22:07
@khk624 What about iOS? Since you have not updated the source for iOS, will it still function if the call to connect() is removed? Thanks.

**Comment by khk624** [comment] 2015-05-26 00:13
It seems iOS had not been updated yet. 
@iadnan Can you please take a look at this?

**Comment by iadnan** [comment] 2015-05-27 00:31
@khk624  looks like you fixed it in Web-App-Sampler-Cordova and not in Connect-SDK-Cordova-API-Sampler .

**Comment by khk624** [comment] 2015-05-27 08:19
@iadnan yes because Cordova API Sampler has no web app tester. We have Web app testing in Web-App-Sampler-Cordova.

**Comment by LukePulverenti** [comment] 2015-05-27 17:27
In the meantime while waiting for iOS, can you confirm the procedure for android? Is it just a matter of updating the code in the cordova plugin, or does this also require SDK library updates? Thanks.

**Comment by iadnan** [comment] 2015-05-27 21:37
@khk624 verified on iOS with  https://github.com/ConnectSDK/Web-App-Sampler-Cordova, its working as expected . @LukePulverenti Can you please verify it as well on iOS and let us know in case of any issues.

**Comment by LukePulverenti** [comment] 2015-05-27 21:42
Yes I'm happy to verify on both platforms, I just need some info on what the setup procedure is. The master branch has not been updated since June 2014, therefore I am using the Connect SDK from that time. So using that as my starting point, it sounds like I need to:

- Update the cordova plugin with these commits:

https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin/commit/2bb4ac327a68453378b4874649918fed24d7a52f

- Then update my own app based on the web app sampler

Is this correct or do I need to also update the native SDK's?

**Comment by LukePulverenti** [comment] 2015-05-28 21:35
Well, just for an update, i reworked my app slightly to match your web app sampler as much as possible. I did not update the cordova plugin. But yes, I can confirm, working as expected. My only problem now is not being able to rejoin sessions that have been previously left, although i need to do a little more debugging to be certain it's not my own problem.

**Comment by LukePulverenti** [comment] 2015-06-05 13:32
Having done more testing, I am unable to receive the same messages in android that I am in iOS. I made the code changes to the plugin, and made sure to call setWebAppSessionListener. Is there a known issue with this?
